"""Assemble submission/src/*.py into a self-contained Kaggle notebook.

The repo stays the source of truth; the notebook is a build artifact:

    python3 submission/build_notebook.py

Then upload submission/arc2_nvarc.ipynb to Kaggle, attach the competition
dataset and the model, and set the accelerator to L4x4 with internet OFF.
"""

import os
import json
import base64
import argparse

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "src")

# Order matters: arc_config first, arc_solver imports arc_loader.
PY_FILES = [
    "arc_config.py",
    "arc_loader.py",
    "arc_decoder.py",
    "arc_solver.py",
    "make_submission.py",
    "starter.py",
]

# Pins from NVARC's pip-install-unsloth-flash-patch.ipynb. The qwen3.patch
# hunks are line-matched to unsloth 2025.9.7, so this pin is load-bearing.
INSTALL = """\
!pip uninstall -y tensorflow
!pip install unsloth==2025.9.7 unsloth_zoo==2025.9.9 numpy==2.2.6 \\
    matplotlib==3.10.6 scikit-learn==1.7.2
!pip install --upgrade --no-deps --no-build-isolation flash-attn"""

# NVARC hardcoded /usr/local/lib/python3.11/dist-packages. Locate it instead:
# the Kaggle image has moved since Dec 2025. Fail loudly if the patch misses --
# unpatched Unsloth silently mishandles batched inference, and the whole DFS
# runs with batch size 4.
PATCH_APPLY = '''\
import base64, os, subprocess, sys

with open("qwen3.patch", "wb") as f:
    f.write(base64.b64decode(PATCH_B64))

import unsloth.models
target = os.path.join(os.path.dirname(unsloth.models.__file__), "qwen3.py")
print("patch target:", target)

r = subprocess.run(["patch", "--binary", "--forward", target, "qwen3.patch"],
                   capture_output=True, text=True)
print(r.stdout, r.stderr)

src = open(target).read()
assert "flash_attn_func(Qnn, Knn, Vnn)" in src, (
    "qwen3.py is NOT patched. Batched DFS decoding needs Unsloth's inference "
    "path to use flash_attn_func with bsz>1. Check that unsloth==2025.9.7 "
    "installed and that the patch hunks still apply."
)
print("OK: unsloth qwen3 inference path patched for batched decoding")'''


def code(source):
    return {"cell_type": "code", "execution_count": None, "metadata": {},
            "outputs": [], "source": source.splitlines(keepends=True)}


def markdown(source):
    return {"cell_type": "markdown", "metadata": {},
            "source": source.splitlines(keepends=True)}


def build(model_slug, out_path):
    with open(os.path.join(SRC, "qwen3.patch"), "rb") as f:
        patch_b64 = base64.b64encode(f.read()).decode()

    cells = [
        markdown(
            "# NVARC port -- ARC Prize 2026 (ARC-AGI-2)\n"
            "\n"
            "Recreation of the ARC Prize 2025 winning solution by Ivan Sorokin and\n"
            "Jean-Francois Puget (NVIDIA), re-pointed at the 2026 competition.\n"
            "Generated by `submission/build_notebook.py` -- edit the sources in\n"
            "`submission/src/`, not this notebook.\n"
            "\n"
            "**Setup:** accelerator `L4x4`, internet **off**, attach the competition\n"
            f"dataset and the Kaggle model `sorokin/{model_slug}`.\n"
        ),
        code(
            "import time, os\n"
            "NOTEBOOK_START = time.time()\n"
            f'os.environ["ARC_MODEL_SLUG"] = "{model_slug}"\n'
            'print("start", time.strftime("%H:%M:%S"))'
        ),
        code(INSTALL),
        code(f'PATCH_B64 = "{patch_b64}"'),
        code(PATCH_APPLY),
    ]

    for name in PY_FILES:
        with open(os.path.join(SRC, name)) as f:
            body = f.read()
        cells.append(code(f"%%writefile {name}\n{body}"))

    cells.append(code(
        "# Write a format-valid submission before any GPU work, so a crash or a\n"
        "# 12h timeout still leaves a scoreable file on disk.\n"
        "import sys; sys.path.insert(0, '.')\n"
        "import arc_config\n"
        "from make_submission import write_fallback\n"
        "write_fallback()"
    ))

    cells.append(code(
        "# Budget is anchored at notebook start, so pip install time counts.\n"
        "end_time = NOTEBOOK_START + arc_config.TOTAL_BUDGET_S - arc_config.SAFETY_MARGIN_S\n"
        'print(f"solver budget: {(end_time - time.time()) / 3600:.2f}h")'
    ))

    cells.append(code(
        "!UNSLOTH_DISABLE_STATISTICS=1 TRITON_PTXAS_PATH=/usr/local/cuda/bin/ptxas \\\n"
        "    OMP_NUM_THREADS=12 python starter.py --end-time {end_time}"
    ))

    cells.append(code(
        "# Rank candidates and overwrite the fallback. Raises if the format is bad.\n"
        "!python make_submission.py --selector kgmon\n"
        'print(f"total elapsed: {(time.time() - NOTEBOOK_START) / 3600:.2f}h")'
    ))

    cells.append(code(
        "import json\n"
        "sub = json.load(open(arc_config.SUBMISSION_PATH))\n"
        "solved = sum(1 for v in sub.values()\n"
        "             for a in v if a['attempt_1'] != [[0]])\n"
        "print(f'{len(sub)} tasks, {sum(len(v) for v in sub.values())} outputs, '\n"
        "      f'{solved} with a real prediction')"
    ))

    nb = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python",
                           "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }

    with open(out_path, "w") as f:
        json.dump(nb, f, indent=1)
    print(f"wrote {out_path} ({len(cells)} cells, model={model_slug})")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--model", default="qwen3_2b_grids15_sft141",
                   help="qwen3_2b_grids15_sft141 (6h, ~22%%) "
                        "or qwen3_4b_grids15_sft139 (12h, ~30%%)")
    p.add_argument("--out", default=os.path.join(HERE, "arc2_nvarc.ipynb"))
    a = p.parse_args()
    build(a.model, a.out)
